---
name: "Deputy/Snowflake Integration"
author: "Fractal River (www.fractalriver.com)"
description: "Fetch data from Deputy API and upload it into Snowflake instance"
runs:
  using: "docker"
  image: "../../../Dockerfile"
