name: deputy_connector
on:
  push:
    branches:
      - main

jobs:
  deputy_snowflake_connector:
    runs-on: ubuntu-latest
    name: Deputy-Snowflake Connector
    steps:
    - uses: actions/checkout@v3
    - name: Test_1
      run: echo "Running from GH!"
    - name: Deploy Deputy Container
      uses: ./.github/actions/deputy_connector
      env:
          TIMESHEETS_ENDPOINT: ${{ secrets.TIMESHEETS_ENDPOINT }}